version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install
  build:
    commands:
      - echo "VITE_API_BASE_URL=https://8d0k7vpis2.execute-api.us-east-1.amazonaws.com/dev" > .env
      - echo "VITE_COGNITO_USER_POOL_ID=us-east-1_fI1DXKZCj" >> .env
      - echo "VITE_COGNITO_CLIENT_ID=jzcfu8" >> .env
      - echo "VITE_COGNITO_REGION=us-east-1" >> .env
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: dist